apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-airflow-dags
  namespace: hcm-datatransfer
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: pv-airflow-dags
  resources:
    requests:
      storage: 5Gi